# Generated by Django 3.2.7 on 2022-03-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Search'},
        ),
        migrations.AlterField(
            model_name='search',
            name='address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
